### ISSUE TITLE
Importing Brands from the offical Woocommerce Brands plugin?

### ISSUE THREAD

**Issue by Chunkford** [titodevera/perfect-woocommerce-brands#11]
Hi Alberto, firstly loving this plugin. Thank you for your time to write it.
Secondly, am I right in thinking you can't import brands from the 'offical' Woocommerce Brands plugin?
I don't see it in the drop-down list in settings.

**Comment by Chunkford** [comment]
Yep, there isn't an option.
So I've done it for you - https://github.com/titodevera/perfect-woocommerce-brands/pull/12

**Comment by Chunkford** [comment]
oh.... just noticed the Ultimate WooCommerce Brand plugin uses the same meta key.
hummmmm.

**Comment by titodevera** [comment]
Merged :)
