### ISSUE TITLE
Product filter widget does not seems to work

### ISSUE THREAD

**Issue by hassandad** [titodevera/perfect-woocommerce-brands#2]
Hello,

I am trying to integrate product filter widget but it does not seems to work and get all the products instead of filter by brand. You can view it here on my website. http://www.marsonline.pk/product-category/dairy/?pwb-brand-filter=almarai .

**Comment by hassandad** [comment]
Ok it seems it works for shop page but not for category page. I get into it and the issue seems this check
if ( !is_admin() && is_post_type_archive( 'product' ) && $query->is_main_query() ) 
 in "pwb_brand_filter" function .

I think there no need to check if !is_admin(). It should work for admin as well. And is_post_type_archive( 'product' ) get false in product category page. If disable this, filter start working in product category page as well.

**Comment by titodevera** [comment]
Solved on new commit, 1.5 RC3, thanks :D
